{
 "title": "Harvester VM Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "count", "label": "count", "query": "5, 10, 20" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(${count}, (avg(rate(kubevirt_vmi_vcpu_seconds[5m])) by (domain, name))) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(${count}, ((kubevirt_vmi_memory_available_bytes - kubevirt_vmi_memory_unused_bytes) / kubevirt_vmi_memory_available_bytes))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Storage Read Traffic Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(${count}, (irate(kubevirt_vmi_storage_read_traffic_bytes_total[5m]))) ",
     "legendFormat": "{{name}}: {{drive}}"
    }
   ]
  },
  {
   "title": "Storage Write Traffic Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(${count}, (irate(kubevirt_vmi_storage_write_traffic_bytes_total[5m]))) ",
     "legendFormat": "{{name}}: {{drive}}"
    }
   ]
  },
  {
   "title": "Network Receive Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "topk(${count}, (irate(kubevirt_vmi_network_receive_bytes_total[5m])*8))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Transmit Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "topk(${count}, (irate(kubevirt_vmi_network_transmit_bytes_total[5m])*8))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Receive Packets (2h)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(${count}, (delta(kubevirt_vmi_network_receive_packets_total[2h])))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Transmit Packets (2h)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(${count}, (delta(kubevirt_vmi_network_transmit_packets_total[2h])))",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}
{
 "title": "Harvester VM Info Detail",
 "description": "Harvester VM Info Detail",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kubevirt_vmi_vcpu_seconds, namespace)"
    }
   },
   {
    "name": "vm",
    "label": "vm",
    "query": {
     "query": "label_values(kubevirt_vmi_vcpu_seconds{namespace=\"$namespace\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(avg(rate(kubevirt_vmi_vcpu_seconds{namespace=\"$namespace\", name=\"$vm\"}[5m])) by (domain, name))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum((kubevirt_vmi_memory_available_bytes{namespace=\"$namespace\", name=\"$vm\"} -kubevirt_vmi_memory_unused_bytes{namespace=\"$namespace\", name=\"$vm\"})/kubevirt_vmi_memory_available_bytes{namespace=\"$namespace\", name=\"$vm\"})"
    }
   ]
  },
  {
   "title": "IO Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_storage_read_traffic_bytes_total{namespace=\"$namespace\", name=\"$vm\"}[5m])",
     "legendFormat": "{{drive}}-read"
    },
    {
     "expr": "irate(kubevirt_vmi_storage_write_traffic_bytes_total{namespace=\"$namespace\", name=\"$vm\"}[5m])",
     "legendFormat": "{{drive}}-write"
    }
   ]
  },
  {
   "title": "IO Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_storage_read_times_ms_total{namespace=\"$namespace\", name=\"$vm\"}[5m])",
     "legendFormat": "{{drive}}-read"
    },
    {
     "expr": "irate(kubevirt_vmi_storage_write_times_ms_total{namespace=\"$namespace\", name=\"$vm\"}[5m])",
     "legendFormat": "{{drive}}-write"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_storage_iops_read_total{namespace=\"$namespace\", name=\"$vm\"}[5m])",
     "legendFormat": "{{drive}}-read"
    },
    {
     "expr": "irate(kubevirt_vmi_storage_iops_write_total{namespace=\"$namespace\", name=\"$vm\"}[5m])",
     "legendFormat": "{{drive}}-writ"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_network_receive_bytes_total{namespace=\"$namespace\", name=\"$vm\"}[5m])*8",
     "legendFormat": "{{interface}}-receive"
    },
    {
     "expr": "irate(kubevirt_vmi_network_transmit_bytes_total{namespace=\"$namespace\", name=\"$vm\"}[5m])*8",
     "legendFormat": "{{interface}}-transmit"
    }
   ]
  }
 ]
}
{
 "title": "Harvester Exporter",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "API Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Read Code - Requests",
   "type": "graph",
   "description": "How many read requests (LIST,GET,WATCH) per second do the apiservers get by code?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{group=~\".*harvester.*\", verb=~\"LIST|GET|WATCH\"}[5m])) by (code, resource, group)"
    }
   ]
  },
  {
   "title": "Write Code - Requests",
   "type": "graph",
   "description": "How many write requests (POST|PUT|PATCH|DELETE) per second do the apiservers get by code?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{group=~\".*harvester.*\", verb=~\"POST|PUT|PATCH|DELETE\"}[5m])) by (code, resource, group)"
    }
   ]
  },
  {
   "title": "Read Request - Duration",
   "type": "graph",
   "description": "How many seconds is the 99th percentile for reading (LIST|WATCH|GET) a given resource?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(apiserver_request_duration_seconds_bucket{group=\"harvesterhci.io\", verb=~\"LIST|WATCH|GET\"}[5m])) by (le, resource))",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "title": "Write Request - Duration",
   "type": "graph",
   "description": "How many seconds is the 99th percentile for writing (POST|PUT|PATCH|DELETE) a given resource?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(apiserver_request_duration_seconds_bucket{group=\"harvesterhci.io\", verb=~\"POST|PUT|PATCH|DELETE\"}[5m])) by (le, resource))",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU Usage (3m avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"harvester-system\",container!=\"\", container!=\"POD\"}[3m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage (3m avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_memory_working_set_bytes{namespace=\"harvester-system\",container!=\"\", container!=\"POD\"}[3m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Network IO (3m avg) / bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{namespace=\"harvester-system\",pod!=\"\"}[3m])) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{namespace=\"harvester-system\",pod!=\"\"}[3m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Webhook", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Webhook Latency  (3m avg) / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(harvester_webhook_latency_seconds_bucket{namespace=\"harvester-system\"}[3m])) by (le, webhook, instance))",
     "legendFormat": "{{webhook}} {{instance}}"
    }
   ]
  },
  { "title": "Controller Reconciliation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Harvester Controller Reconciliation Number",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (controller)(irate(controller_reconcile_total{job=\"harvester\"}[3m]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Harvester Controller Reconciliation Success Number",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, result)(irate(controller_reconcile_total{job=\"harvester\", result=\"success\"}[3m]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Harvester Controller Reconciliation Error Number",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, result)(irate(controller_reconcile_total{job=\"harvester\", result=\"error\"}[3m]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Harvester Controller Reconciliation Error Ignore Number",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, result)(irate(controller_reconcile_total{job=\"harvester\", result=\"error_ignore\"}[3m]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Harvester Webhook Controller Reconciliation Number",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (controller)(irate(controller_reconcile_total{job=\"harvester-webhook\"}[3m]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Harvester Webhook Controller Reconciliation Success Number",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, result)(irate(controller_reconcile_total{job=\"harvester-webhook\", result=\"success\"}[3m]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Harvester Webhook Controller Reconciliation Error Number",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, result)(irate(controller_reconcile_total{job=\"harvester-webhook\", result=\"error\"}[3m]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Harvester Webhook Controller Reconciliation Error Ignore Number",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, result)(irate(controller_reconcile_total{job=\"harvester-webhook\", result=\"error_ignore\"}[3m]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Harvester Controller Reconciliation Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(controller_reconcile_time_seconds_bucket{job=\"harvester\"}[5m])) by (le, controller))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Harvester Webhook Controller Reconciliation Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(controller_reconcile_time_seconds_bucket{job=\"harvester-webhook\"}[5m])) by (le, controller))",
     "legendFormat": "{{ controller }}"
    }
   ]
  },
  { "title": "Work Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Harvester Work Queue Grow Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=~\"harvester\"}[5m])) by (instance, name, kind)",
     "legendFormat": "{{name}} {{kind}} {{instance}}"
    }
   ]
  },
  {
   "title": "Harvester Work Queue Retry Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_retries_total{job=~\"harvester\"}[5m])) by (instance, name, kind)",
     "legendFormat": "{{name}} {{kind}} {{instance}}"
    }
   ]
  },
  {
   "title": "Harvester Work Queue Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{job=~\"harvester\"}[5m])) by (instance, name, kind, le))",
     "legendFormat": "{{name}} {{kind}} {{instance}}"
    }
   ]
  },
  {
   "title": "Harvester Work Queue Depth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(workqueue_depth{job=~\"harvester\"}) by (instance, name, kind)",
     "legendFormat": "{{name}} {{kind}} {{instance}}"
    }
   ]
  },
  {
   "title": "Harvester Webhook Work Queue Grow Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=~\"harvester-webhook\"}[5m])) by (instance, name, kind)",
     "legendFormat": "{{name}} {{kind}} {{instance}}"
    }
   ]
  },
  {
   "title": "Harvester Webhook Work Queue Retry Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_retries_total{job=~\"harvester-webhook\"}[5m])) by (instance, name, kind)",
     "legendFormat": "{{name}} {{kind}} {{instance}}"
    }
   ]
  },
  {
   "title": "Harvester Webhook Work Queue Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{job=~\"harvester-webhook\"}[5m])) by (instance, name, kind, le))",
     "legendFormat": "{{name}} {{kind}} {{instance}}"
    }
   ]
  },
  {
   "title": "Harvester Webhook Work Queue Depth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(workqueue_depth{job=~\"harvester-webhook\"}) by (instance, name, kind)",
     "legendFormat": "{{name}} {{kind}} {{instance}}"
    }
   ]
  },
  { "title": "Go Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (go_goroutines{namespace=\"harvester-system\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Stack Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by ( pod) (go_memstats_stack_sys_bytes{namespace=\"harvester-system\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "GC Duration / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{namespace=\"harvester-system\"}[3m]) / rate(go_gc_duration_seconds_count{namespace=\"harvester-system\"}[3m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Next GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by ( pod) (go_memstats_next_gc_bytes{namespace=\"harvester-system\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}